<?php
/** @var $block Magento\ReCaptchaUi\Block\ReCaptcha */
?>
<div class="input-holder">
    <div
        class="form-control field-recaptcha"
        id="<?= /* @noEscape */ $block->getRecaptchaId() ?>-container"
        data-bind="scope:'<?= /* @noEscape */ $block->getRecaptchaId() ?>'"
    >
        <!-- ko template: getTemplate() --><!-- /ko -->
    </div>

    <script type="text/x-magento-init">
    {
        "#<?= /* @noEscape */ $block->getRecaptchaId() ?>-container": {
            "Magento_Ui/js/core/app": <?= /* @noEscape */ $block->getJsLayout() ?>
        }
    }
    </script>
</div>
